### ISSUE TITLE
Erro ao executar a php artisan migrate

### ISSUE THREAD

**Issue by LucasAriatti** [EutruTepit/TrabWeb2022#16]
Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'produto' already exists (SQL: create table `produto` (`deleted_at` timestamp null, `id` bigint unsigned not null auto_increment primary key, `nome` varchar(200) not null, `descricao` varchar(500) not null, `preco` double(14, 2) not null, 
`dataLancamento` date not null, `idFornecedor` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at C:\xampp\htdocs\TrabWeb2022\vendor\laravel\framework\src\Illuminate\Database\Connection.php:745
    741▕         // If an exception occurs when attempting to run a query, we'll format the error
    742▕         // message to include the bindings with SQL, which will make this exception a
    743▕         // lot more helpful to the developer instead of just the database's errors.
    744▕         catch (Exception $e) {
  ➜ 745▕             throw new QueryException(
    746▕                 $query, $this->prepareBindings($bindings), $e      
    747▕             );
    748▕         }
    749▕     }

  1   C:\xampp\htdocs\TrabWeb2022\vendor\laravel\framework\src\Illuminate\Database\Connection.php:530
      PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'produto' already exists")

  2   C:\xampp\htdocs\TrabWeb2022\vendor\laravel\framework\src\Illuminate\Database\Connection.php:530
      PDOStatement::execute()

**Comment by EutruTepit** [comment]
Na dev já deveria estar atualizado. tenta dar drop database no banco.

**Comment by EutruTepit** [comment]
Tá eu revisei e tava com problema msm, o problema começou com o commit #15. Restaurei o arquivo, só selecionar a branch q tu quer atualizar dar merge da dev.
